# File: k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-sale-api
  namespace: flash-sale
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flash-sale-api
  template:
    metadata:
      labels:
        app: flash-sale-api
        version: v1
    spec:
      containers:
      - name: api
        image: flash-sale-api:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: flash-sale-secrets
              key: redis-url
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: flash-sale-config
              key: kafka-brokers
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: flash-sale-config
              key: mysql-host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flash-sale-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flash-sale-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          value: "flash_sale"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: flash-sale-api
  namespace: flash-sale
spec:
  selector:
    app: flash-sale-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

